# Generated by Django 4.2.3 on 2023-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'moderator'), ('member', 'member')], default='member', max_length=10, verbose_name='user_role'),
        ),
    ]
