version: '3'

services:

  db:
    image: postgres
    container_name: db_app
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: drf_lms

  app:
    build: .
    container_name: app_container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  redis:
    image: redis:7.0.2-alpine
    container_name: redis_app
    command: redis-server --save 20 1 loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - .\data\cache:/data
