# Generated by Django 4.2.3 on 2023-07-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=250, unique=True, verbose_name='course_title')),
                ('course_preview', models.ImageField(blank=True, null=True, upload_to='courses_previews', verbose_name='course_preview')),
                ('course_description', models.TextField(blank=True, null=True, verbose_name='course_description')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=250, verbose_name='lesson_title')),
                ('lesson_description', models.TextField(blank=True, null=True, verbose_name='lesson_description')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='lessons_previews', verbose_name='lesson_preview')),
                ('link_to_video', models.URLField(blank=True, max_length=250, null=True, verbose_name='link_to_lesson_video')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course', to='courses.course', verbose_name='lesson_course')),
            ],
        ),
    ]
