# Generated by Django 4.2.3 on 2023-07-18 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_payment_paid_course_alter_payment_paid_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='course_user'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='lesson_user'),
        ),
    ]
