# Generated by Django 4.2.3 on 2023-07-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_price_alter_lesson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='courses.lesson', verbose_name='paid_lesson'),
        ),
    ]
