# Generated by Django 4.2.3 on 2023-07-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_alter_payment_paid_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='payment_sum'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='payment_user'),
        ),
    ]
