# Generated by Django 4.2.3 on 2023-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_payment_payment_sum_alter_payment_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='payment_url'),
        ),
    ]
