# Generated by Django 4.2.3 on 2023-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='payment_id'),
        ),
    ]
